name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source (ignore warnings and info)
        run: |
          OUTPUT=$(flutter analyze || true)
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q "error •"; then
            echo "❌ Analyzer found errors"
            exit 1
          else
            echo "✅ No analyzer errors found"
          fi

      - name: Run tests
        run: flutter test
